Repository clusternet/clusternet, pull requests merged in 2021-08, with the labels that each got.

#43 add client-go wrapper and example codes
  examples/clientgo/READEME.md
  examples/clientgo/demo.go
  go.mod
  go.sum
  pkg/registry/shadow/template/rest.go
  pkg/wrappers/clientgo/wrapper.go
  pkg/wrappers/clientgo/wrapper_test.go
Labels: kind/bug, kind/documentation, kind/feature

#45 support listing with resourceVersion
  pkg/registry/shadow/template/rest.go
Labels: kind/feature

#48 notify base handler when manifests get changed
  .github/workflows/ci.yml
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/base/base_test.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/hub/deployer/deployer.go
  pkg/hub/hub.go
  pkg/registry/shadow/template/rest.go
Labels: kind/feature

#50 fix manifest name and codec encoding
  go.mod
  go.sum
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#49 deploy descriptions with generic deployer
  manifests/crds/apps.clusternet.io_descriptions.yaml
  pkg/apis/apps/v1alpha1/description.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
  pkg/hub/deployer/utils.go
  pkg/utils/kubeconfig.go
  pkg/utils/kubeconfig_test.go
Labels: kind/feature

#53 inject clusternet app finalizer only when needed
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
Labels: kind/enhancement

#52 compatible empty clusterID when listing ManagedCluster
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/kubeconfig.go
Labels: kind/bug

#54 remove unmatched Base label from Manifest
  pkg/hub/deployer/deployer.go
Labels: kind/enhancement

#33 update deployment yaml with new versions and features
  README.md
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_apiservice.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  docs/images/clusternet-apps-concepts.png
  examples/applications/helm-chart-mysql.yaml
  examples/applications/nginx-deployment.yaml
  examples/applications/nginx-svc.yaml
  examples/applications/subscription.yaml
  manifests/samples/helm_chart.yaml
  manifests/samples/subscription.yaml
  pkg/hub/deployer/generic/generic.go
Labels: kind/feature, kind/change

#59 mitigate agent npe on secret storing
  pkg/agent/agent.go
Labels: kind/bug

#60 skip shadow GVKs in clusternet group
  pkg/hub/apiserver/shadow/apiserver.go
Labels: kind/bug

#63 fix wrapper on group names with dot
  pkg/wrappers/clientgo/wrapper.go
  pkg/wrappers/clientgo/wrapper_test.go
Labels: kind/bug

#62 lower priority of shadow GVK
  deploy/hub/clusternet_hub_apiservice.yaml
Labels: kind/bug

#67 update README: PARENTURL also support port number
  README.md
Labels: kind/documentation

#65 remove protobuf serializer and append namespace label when listing
  go.mod
  go.sum
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#70 reuse objects retrieved from tombstone
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/clusters/clusterregistrationrequest/clusterregistrationrequest_controller.go
  pkg/controllers/misc/secret/secret.go
Labels: kind/bug

#69 remove redundant objects when subscription changed
  README.md
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/helm/helm.go
Labels: kind/enhancement

#72 fix listing resources over all namespaces
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#74 add missing informer cache sync in deployer
  pkg/hub/deployer/deployer.go
Labels: kind/enhancement

#75 register apps scheme in recorder
  pkg/hub/deployer/deployer.go
Labels: kind/bug

#78 skip not-found error when removing from child cluster
  pkg/hub/deployer/generic/generic.go
Labels: kind/bug

#77 protect feed source object from getting deleted when referred by in-use subscriptions
  pkg/agent/deployer.go
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/features/features.go
  pkg/hub/approver/approver.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/helm/helm.go
  pkg/known/annotations.go
  pkg/known/constant.go
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/transformer.go
  pkg/utils/feed.go
  pkg/utils/labels.go
  pkg/utils/patch.go
  pkg/utils/patch_test.go
  pkg/utils/rbac.go
Labels: kind/feature

#61 update OverrideConfig type and add listers to localizer
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  pkg/apis/apps/v1alpha1/globalization.go
  pkg/apis/apps/v1alpha1/localization.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/hub/localizer/localizer.go
Labels: kind/apis, kind/enhancement

#86 optimize apps controllers sync logic
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/misc/secret/secret.go
Labels: kind/enhancement

#94 comment out checking cluster type on registration
  README.md
  pkg/agent/option.go
  pkg/apis/clusters/v1beta1/types.go
Labels: kind/bug

#93 add more verbose log when handling
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
Labels: kind/enhancement

#95 update apps concepts image
  docs/images/clusternet-apps-concepts.png
Labels: kind/documentation

#88 add more golang linters and address lint issues
  Makefile
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/agent/deployer.go
  pkg/agent/status_manager.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/misc/secret/secret.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/approver/approver.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/generic/utils.go
  pkg/hub/hub.go
  pkg/registry/proxies/socket/subresources/proxy.go
  pkg/registry/shadow/template/rest.go
  pkg/utils/feed_test.go
  pkg/utils/rbac.go
Labels: kind/enhancement
