Repository clusternet/clusternet, pull requests merged in 2021-09, with the labels that each got.

#90 dispatch feeds to new matching clusters
  pkg/controllers/apps/subscription/subscription.go
  pkg/hub/deployer/deployer.go
  pkg/hub/hub.go
Labels: kind/enhancement

#97 initializes description.raw to avoid index out of range
  pkg/hub/deployer/deployer.go
Labels: kind/bug

#98 reuse app deployer credentials to collect cluster status when available
  pkg/agent/deployer/constant.go
  pkg/agent/status_manager.go
Labels: kind/bug

#101 filter out empty overrides before applying
  pkg/hub/localizer/patch.go
  pkg/hub/localizer/patch_test.go
Labels: kind/bug

#73 add samples for localization and globalization
  examples/applications/globalization.yaml
  examples/applications/localization.yaml
Labels: kind/documentation

#103 validate override value first before applying
  pkg/hub/localizer/patch.go
  pkg/hub/localizer/patch_test.go
Labels: kind/enhancement

#76 deploy clusternet 0.4.0
  README.md
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  examples/applications/globalization.yaml
  examples/applications/localization.yaml
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  pkg/apis/apps/v1alpha1/globalization.go
  pkg/apis/apps/v1alpha1/localization.go
Labels: kind/documentation, kind/change

#104 priority sort bugfix
  pkg/hub/localizer/localizer.go
Labels: kind/bug

#108 fix nil hrStatus
  pkg/utils/deployer.go
Labels: kind/bug

#105 append manifest labels on template updates
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#107 record last error in exponential backoff retry
  pkg/agent/status_manager.go
  pkg/hub/approver/approver.go
  pkg/utils/deployer.go
  pkg/utils/rbac.go
Labels: kind/enhancement

#109 fix jsonpatch path in examples
  examples/applications/localization.yaml
Labels: kind/documentation

#110 use a whitespace explicitly for helm overrides
  pkg/hub/deployer/deployer.go
  pkg/hub/localizer/localizer.go
  pkg/utils/deployer.go
Labels: kind/bug

#111 fix invalid spec.replicas type during json patching
  examples/applications/localization.yaml
Labels: kind/documentation

#114 start clusternet informer on agent side
  pkg/agent/deployer/deployer.go
Labels: kind/bug

#116 fix nil annotations when transforming objects
  pkg/registry/shadow/template/transformer.go
Labels: kind/bug

#117 fix variable typo in agent deployer
  pkg/agent/deployer/deployer.go
Labels: kind/bug

#123 label Subscription self uid
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/subscription/subscription.go
Labels: kind/feature

#119 updated LICENSES
  LICENSE
  LICENSES/OTHER_LICENSES
Labels: kind/change

#125 add curl usage to access child cluster
  README.md
Labels: kind/documentation

#131 support continue value when listing in chunks
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#100 cluster lifecycle controller in hub
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/option.go
  pkg/agent/status_manager.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller_test.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/hub/deployer/deployer.go
  pkg/hub/hub.go
Labels: kind/enhancement

#132 fix manifests updating
  cmd/clusternet-hub/app/app.go
  go.mod
  pkg/agent/deployer/deployer.go
  pkg/agent/deployer/generic/generic.go
  pkg/agent/deployer/helm/helm.go
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterregistrationrequest/clusterregistrationrequest_controller.go
  pkg/controllers/misc/secret/secret.go
  pkg/hub/apiserver/apiserver.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/approver/approver.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
  pkg/hub/hub.go
  pkg/hub/localizer/localizer.go
  pkg/registry/shadow/template/rest.go
  pkg/utils/deployer.go
Labels: kind/bug

#138 not wait for cache sync to support Kubernetes version skew
  pkg/hub/hub.go
Labels: kind/bug

#130 admission webhook must support dry run mode
  README.md
Labels: kind/documentation

#102 install shadow GVKs for newly created CRDs
  go.mod
  go.sum
  pkg/exchanger/exchanger.go
  pkg/hub/apiserver/apiserver.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/hub.go
  pkg/known/constant.go
  pkg/registry/shadow/template/rest.go
Labels: kind/feature

#141 remediate security vulnerabilities in dependencies
  go.mod
  go.sum
Labels: kind/security

#142 remediate security vulnerability of jwt-go
  go.mod
  go.sum
Labels: kind/security
