Repository clusternet/clusternet, pull requests merged in 2021-12, with the labels that each got.

#197 fix cluster label parsing
  pkg/agent/agent.go
Labels: kind/documentation

#193 add helm repo auth support
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/agent/deployer/deployer.go
  pkg/agent/deployer/helm/helm.go
  pkg/apis/apps/v1alpha1/helm.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/hub/approver/approver.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/chart.go
  pkg/utils/deployer.go
Labels: kind/feature

#198 upgrade runc to v1.0.3 to mitigate CVE-2021-43784
  go.mod
  go.sum
Labels: kind/security

#202 reconciling Description when HelmChart got changed
  pkg/agent/deployer/generic/generic.go
  pkg/controllers/apps/description/description.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
Labels: kind/bug

#204 add scheduler framework
  cmd/clusternet-scheduler/app/app.go
  cmd/clusternet-scheduler/scheduler.go
  go.mod
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/known/constant.go
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/algorithm/interface.go
  pkg/scheduler/apis/types.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/interfaces/interface.go
  pkg/scheduler/framework/interfaces/interface_copied.go
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/metrics_recorder.go
  pkg/scheduler/framework/runtime/registry.go
  pkg/scheduler/framework/runtime/waiting_susbcriptions_map.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/metrics/profile_metrics.go
  pkg/scheduler/options/options.go
  pkg/scheduler/parallelize/error_channel.go
  pkg/scheduler/parallelize/error_channel_test.go
  pkg/scheduler/parallelize/parallelism.go
  pkg/scheduler/parallelize/parallelism_test.go
  pkg/scheduler/scheduler.go
  pkg/utils/leaderelection.go
Labels: kind/feature, kind/apis

#205 introducing ControllerOptions for common use
  cmd/clusternet-agent/agent.go
  cmd/clusternet-agent/app/app.go
  cmd/clusternet-agent/app/options.go
  cmd/clusternet-scheduler/app/app.go
  deploy/agent/clusternet_agent_deployment.yaml
  pkg/agent/agent.go
  pkg/agent/constant.go
  pkg/agent/deployer/deployer.go
  pkg/agent/status_manager.go
  pkg/hub/hub.go
  pkg/known/constant.go
  pkg/scheduler/options/options.go
  pkg/scheduler/scheduler.go
  pkg/utils/deployer.go
  pkg/utils/kubeconfig.go
  pkg/utils/options.go
Labels: kind/apis, kind/enhancement

#206 update Clusternet architecture
  README.md
  docs/images/clusternet-arch.png
Labels: kind/documentation

#207 minor update Clusternet architecture image
  docs/images/clusternet-arch.png
Labels: kind/documentation

#203 API change: add taints and tolerations
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, kind/apis

#210 add taints and tolerations
  go.mod
  go.sum
  pkg/controllers/apps/subscription/subscription.go
  pkg/hub/deployer/deployer.go
  pkg/utils/deployer.go
Labels: kind/feature

#209 supporting running clusternet-hub on k3s
  cmd/clusternet-hub/app/app.go
  deploy/hub/clusternet_hub_deployment.yaml
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
  pkg/hub/hub.go
  pkg/hub/options/options.go
  pkg/known/constant.go
  pkg/utils/kubeconfig.go
Labels: kind/feature

#211 configurable clusternet reserved namespace
  pkg/apis/apps/v1alpha1/manifest.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/hub/apiserver/apiserver.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/deployer/deployer.go
  pkg/hub/hub.go
  pkg/hub/localizer/localizer.go
  pkg/hub/options/options.go
  pkg/known/constant.go
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/transformer_test.go
  pkg/utils/feed.go
Labels: kind/feature, kind/enhancement

#213 only register resources with the highest priority
  go.mod
  go.sum
  pkg/hub/apiserver/apiserver.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/apiserver/shadow/priority.go
  pkg/hub/hub.go
Labels: kind/bug

#216 add jitter factor for socket controller run
  pkg/controllers/proxies/sockets/socket_controller.go
Labels: kind/enhancement

#219 fix agent run loop
  pkg/agent/agent.go
Labels: kind/bug

#214 use kubectl-clusternet plugin to visit child clusters
  docs/tutorials/visiting-child-clusters-with-rbac.md
Labels: kind/documentation

#212 deploy clusternet with v0.7.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
  deploy/scheduler/clusternet_scheduler_rbac.yaml
  docs/developer-guide.md
  docs/tutorials/installing-clusternet-the-hard-way.md
  docs/tutorials/installing-clusternet-with-helm.md
Labels: kind/documentation

#222 release scheduler binary
  .goreleaser.yml
Labels: kind/change

#224 example on using private helm repo
  deploy/templates/helm-chart-private-repo.yaml
  docs/tutorials/deploying-applications-to-multiple-clusters.md
Labels: kind/documentation

#225 apply timeout for helm operations
  pkg/utils/chart.go
Labels: kind/enhancement
