Repository clusternet/clusternet, pull requests merged in 2021-11, with the labels that each got.

#170 trim dry-run results before storing
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/trimmer.go
  pkg/registry/shadow/template/trimmer_test.go
Labels: kind/bug

#173 supports resources with skew versions
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/utils.go
  pkg/hub/apiserver/shadow/utils_test.go
Labels: kind/feature

#178 do not trim metadata uid
  pkg/registry/shadow/template/trimmer.go
  pkg/registry/shadow/template/trimmer_test.go
Labels: kind/bug

#177 not blocking resource deletion when clusters got lost
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/hub/deployer/generic/generic.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/deployer.go
Labels: kind/bug

#179 customizing labels on cluster registeration
  manifests/crds/clusters.clusternet.io_clusterregistrationrequests.yaml
  pkg/agent/agent.go
  pkg/agent/constant.go
  pkg/agent/option.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/hub/approver/approver.go
Labels: kind/feature

#181 fix description controller cannot reconcile issue
  pkg/utils/deployer.go
Labels: kind/bug

#92 prune redundant labels on HelmChart and Manifest
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/hub/deployer/deployer.go
  pkg/utils/deployer.go
  pkg/utils/feed.go
  pkg/utils/feed_test.go
Labels: kind/enhancement

#182 add docs on Kubernetes version skew
  README.md
Labels: kind/documentation

#155 bump clusternet deploy image to v0.6.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
Labels: kind/change

#183 supports visiting child clusters when anonymous auth is not allowed
  deploy/hub/clusternet_bootstrap_rbac.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/hub/clusternet_hub_rbac.yaml
  docs/tutorials/visiting-child-clusters-with-rbac.md
Labels: kind/documentation, kind/feature

#165 removing deprecated field ParentAPIServerURL
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/status_manager.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/change, kind/apis

#185 add contact info
  README.md
Labels: kind/documentation

#187 add note on image registry
  README.md
  docs/tutorials/installing-clusternet-the-hard-way.md
Labels: kind/documentation

#188 fix vulnerability found in containerd and image-spec
  go.mod
  go.sum
Labels: kind/security

#191 add roadmap
  ROADMAP.md
Labels: kind/documentation

#83 mitigate manifest name with hyphens
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/rest_test.go
Labels: kind/bug
