Repository clusternet/clusternet, pull requests merged in 2022-01, with the labels that each got.

#231 rebase code in workflow CI
  .github/workflows/ci.yml
Labels: kind/workflow

#227 add support "app.kubernetes.io/component" to find apiserver pod
  pkg/controllers/clusters/clusterstatus/network.go
  pkg/controllers/clusters/clusterstatus/network_test.go
Labels: kind/enhancement

#233 clusternet got a logo
  README.md
  docs/images/clusternet-horizontal-color.png
  docs/images/clusternet-in-a-nutshell.png
Labels: kind/documentation

#232 use a GitHub Actions bot user as committer
  .github/workflows/ci.yml
Labels: kind/workflow

#239 return immediately if no clusters match the cluster affinity
  pkg/scheduler/algorithm/generic.go
Labels: kind/bug

#240 update readme with core features
  README.md
Labels: kind/documentation

#241 bump golang version to 1.16
  .github/workflows/ci.yml
  Makefile
  go.mod
  go.sum
Labels: kind/change
