Repository clusternet/clusternet, pull requests merged in 2022-03, with the labels that each got.

#242 fix changes rolling back in child cluster
  pkg/agent/deployer/deployer.go
  pkg/agent/deployer/generic/generic.go
  pkg/hub/deployer/generic/generic.go
  pkg/utils/deployer.go
Labels: kind/bug

#226 plumb new feature gate Recovery
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
  pkg/features/features.go
  pkg/utils/deployer.go
Labels: kind/feature, do-not-merge/hold

#255 fully support OCI-based helm charts
  README.md
  cmd/clusternet-hub/hub.go
  cmd/clusternet-scheduler/scheduler.go
  docs/tutorials/deploying-applications-to-multiple-clusters.md
  examples/oci/oci-chart-mysql.yaml
  go.mod
  go.sum
  pkg/hub/deployer/deployer.go
  pkg/utils/chart.go
  pkg/utils/deployer.go
Labels: kind/feature

#258 fix containerd CVE-2022-23648
  go.mod
  go.sum
Labels: kind/security

#251 add local running script to establish local env immediately
  README.md
  docs/tutorials/quick-installing-clusternet-locally.md
  hack/local-running.sh
Labels: kind/documentation

#260 fix crd storage race condition
  pkg/hub/apiserver/shadow/customresource_handler.go
Labels: kind/bug

#263 fix resource cannot sync issue
  pkg/known/constant.go
  pkg/utils/deployer.go
Labels: kind/bug

#265 add API for dividing scheduling
  manifests/crds/apps.clusternet.io_bases.yaml
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/algorithm/generic.go
Labels: kind/change, kind/apis

#269 configurable Helm release name in child clusters
  examples/applications/helm-chart-mysql.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/chart.go
Labels: kind/feature, kind/apis

#270 add tests against golang 1.18
  .github/workflows/ci.yml
  go.mod
  go.sum
  hack/tools.go
Labels: kind/workflow

#272 introducing new field Overrides for HelmRelease
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/agent/deployer/helm/helm.go
  pkg/apis/apps/v1alpha1/helm.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/chart.go
  pkg/utils/deployer.go
Labels: kind/bug, kind/change, kind/apis
