Repository clusternet/clusternet, pull requests merged in 2022-11, with the labels that each got.

#514 add list verb to clusternet:hub clusterRole
  deploy/hub/clusternet_hub_rbac.yaml
Labels: kind/enhancement

#518 use discovery v1beta1
  pkg/agent/agent.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/hub/hub.go
  pkg/utils/endpointslice.go
Labels: kind/bug

#520 aggregate work nodes labels with threshold
  pkg/agent/constant.go
  pkg/agent/option.go
  pkg/agent/status_manager.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller_test.go
Labels: kind/feature

#523 bugfix: fix the improper usage of `version` package
  pkg/agent/agent.go
  pkg/hub/approver/approver.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: kind/bug

#529 only enable service import/export controllers after EndpointSlice v1beta1 promoted
  pkg/agent/agent.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/hub/hub.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: kind/enhancement

#532 only discovery endpointslice for k8s upper than 1.21.0
  pkg/agent/agent.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/hub/hub.go
  pkg/utils/endpointslice.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: kind/bug

#524 add Subscription SchedulingByGroup configuration support clusters grouping
  examples/scheduling-group/nginx-deployment.yaml
  examples/scheduling-group/nginx-svc.yaml
  examples/scheduling-group/subscription-dynamic-dividing.yaml
  examples/scheduling-group/subscription-replication.yaml
  examples/scheduling-group/subscription-static-dividing.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/algorithm/generic.go
Labels: kind/feature

#534 fix missing status update of description
  pkg/agent/deployer/generic/generic.go
  pkg/utils/deployer.go
Labels: kind/bug

#535 update subGroup example fileds
  examples/scheduling-group/subscription-dynamic-dividing.yaml
Labels: kind/bug

#533 sort the clusters by descending order of decimal part in dynamicDivideReplicas
  pkg/scheduler/framework/plugins/defaultassigner/algorithm.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm_test.go
Labels: kind/bug

#537 update RBAC rules for clusternet-agent running in capi
  pkg/controllers/clusters/clusterlifecycle/discovery/manifest.go
Labels: kind/bug

#539 fix bindingClusters not update and generic description cannot delete
  pkg/hub/deployer/generic/generic.go
  pkg/scheduler/scheduler.go
Labels: kind/bug

#542 non blocking callback handler for feature gate Recovery
  pkg/agent/deployer/generic/generic.go
  pkg/utils/deployer.go
Labels: kind/bug

#544 update README
  README.md
  ROADMAP.md
Labels: kind/documentation

#540 bump container images to v0.13.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change

#546 add subGroup unit test
  pkg/scheduler/algorithm/generic_test.go
Labels: kind/tests
