Repository clusternet/clusternet, pull requests merged in 2022-06, with the labels that each got.

#354 replica predictor scheduling plugin
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/scheduler/default_plugins.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic.go
  pkg/scheduler/framework/plugins/names/names.go
  pkg/scheduler/framework/plugins/predictor/predictor.go
  pkg/scheduler/framework/plugins/registry.go
Labels: kind/feature

#361 update deployment images to v0.10.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change

#362 collect cpu/mem usage and podStatistics for metrics server
  deploy/agent/clusternet_agent_rbac.yaml
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/agent.go
  pkg/agent/constant.go
  pkg/agent/option.go
  pkg/agent/status_manager.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/feature

#364 fix containerd CVE-2022-31030
  go.mod
  go.sum
Labels: kind/security

#366 add dynamic dividing API
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm_test.go
Labels: kind/feature, kind/apis

#371 update clusternet deployment files
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change, do-not-merge/hold

#376 revert "update clusternet deployment files (#371)"
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change

#381 remove go routine for store parent cluster secret
  .gitignore
  pkg/agent/agent.go
Labels: kind/bug

#383 add scheduling loop admission
  pkg/scheduler/framework/plugins/defaultassigner/algorithm.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/utils/slice.go
Labels: kind/enhancement

#384 add human readable printer format
  go.mod
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/registry/shadow/printers/interface.go
  pkg/registry/shadow/printers/internalversion/printers.go
  pkg/registry/shadow/printers/storage/storage.go
  pkg/registry/shadow/printers/tablegenerator.go
  pkg/registry/shadow/printers/util/helpers.go
  pkg/registry/shadow/template/rest.go
Labels: kind/feature

#378 high availability clusternet-hub
  cmd/clusternet-hub/app/app.go
  deploy/hub/clusternet_hub_deployment.yaml
  go.mod
  pkg/controllers/misc/leasegc/leasegc.go
  pkg/exchanger/exchanger.go
  pkg/hub/apiserver/apiserver.go
  pkg/hub/hub.go
  pkg/hub/hub_test.go
  pkg/hub/options/options.go
Labels: kind/feature

#388 add scheduler cycle state
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/algorithm/interface.go
  pkg/scheduler/framework/interfaces/cycle_state.go
  pkg/scheduler/framework/interfaces/cycle_state_test.go
  pkg/scheduler/framework/interfaces/interface.go
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm_test.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic.go
  pkg/scheduler/framework/plugins/defaultassigner/static.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder_test.go
  pkg/scheduler/framework/plugins/predictor/predictor.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration_test.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/scheduler.go
Labels: kind/change

#389 use sepearte clientset for election
  pkg/agent/agent.go
  pkg/hub/hub.go
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#393 clean up unused constants in predictor
  pkg/predictor/apis/types.go
Labels: kind/cleanup

#391 add env for cluster-cidr and service-cidr
  deploy/agent/clusternet_agent_deployment.yaml
  pkg/controllers/clusters/clusterstatus/network.go
Labels: kind/feature

#397 enable linter gci
  .golangci.yml
  Makefile
  pkg/agent/agent.go
  pkg/agent/status_manager.go
  pkg/controllers/apps/feedinventory/statefulset/statefulset.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/utils/feed_test.go
Labels: kind/workflow

#398 fix statefulset feedinventory
  pkg/controllers/apps/feedinventory/registry.go
Labels: kind/bug

#395 add scale functionality to dynamic assigner
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/interfaces/types_test.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm_test.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic_test.go
Labels: kind/feature

#399 improving scheduler enqueue performance
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#396 aggregate common labels from nodes
  go.mod
  pkg/agent/status_manager.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller_test.go
  pkg/known/labels.go
Labels: kind/feature

#400 transfer available replicas only if dynamic dividing
  docs/tutorials/static-weight-scheduling-to-multiple-clusters.md
  examples/static-dividing-scheduling/subscription.yaml
  pkg/scheduler/algorithm/generic.go
Labels: kind/bug
