Repository clusternet/clusternet, pull requests merged in 2022-09, with the labels that each got.

#469 add random fake uid when skipping validating objects
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#471 Forget workqueue key when scheduler success
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#472 add syncHandlerFunc for feedinventory controller
  pkg/controllers/apps/feedinventory/feedinventory.go
  pkg/hub/deployer/deployer.go
Labels: kind/enhancement

#474 use bool point for AppPusher
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/deployer.go
Labels: kind/enhancement

#467 custom helm install/upgrade extras flags
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/chart.go
  pkg/utils/deployer.go
Labels: kind/feature

#481 bump build image and go version
  .github/workflows/release.yml
  Makefile
Labels: kind/workflow

#482 add nfd feature example
  deploy/hub/nodefeaturerule-crd.yaml
  examples/scheduling-with-nfd/day0/globalization.yaml
  examples/scheduling-with-nfd/day0/helm-chart-nfd.yaml
  examples/scheduling-with-nfd/day0/node-feature-rule.yaml
  examples/scheduling-with-nfd/day0/subscription.yaml
  examples/scheduling-with-nfd/day1/nginx-deployment.yaml
  examples/scheduling-with-nfd/day1/subscription.yaml
  manifests/crds/nodefeaturerule-crd.yaml
Labels: kind/examples

#477 support helm release reinstall
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/utils/deployer.go
Labels: kind/enhancement

#487 fix merging TargetClusters
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/interfaces/types_test.go
Labels: kind/bug

#489 auto discover clusters created by cluster-api
  deploy/templates/clusternet_clusterapi_secret.yaml
  go.mod
  go.sum
  pkg/controllers/clusters/clusterlifecycle/discovery/discovery.go
  pkg/controllers/clusters/clusterlifecycle/discovery/manifest.go
  pkg/controllers/clusters/clusterlifecycle/discovery/manifest_test.go
  pkg/controllers/clusters/clusterlifecycle/discovery/provider.go
  pkg/controllers/clusters/clusterlifecycle/discovery/provider_test.go
  pkg/hub/hub.go
  pkg/hub/options/options.go
  pkg/utils/kubeconfig.go
Labels: kind/feature

#490 update capi docs and warning logs
  README.md
  pkg/controllers/clusters/clusterlifecycle/discovery/discovery.go
Labels: kind/documentation

#491 pass down extra headers with prefix clusternet
  pkg/exchanger/exchanger.go
  pkg/known/headers.go
Labels: kind/feature

#492 ignore non-harmful missing parent storage errors
  pkg/hub/apiserver/shadow/apiserver.go
Labels: kind/enhancement

#496 supports shadowing crd itself
  pkg/registry/shadow/printers/tablegenerator.go
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/trimmer.go
Labels: kind/feature

#495 bump helm version to 3.8.2
  go.mod
  go.sum
Labels: kind/bug

#444 update deployment files for clusternet v0.12.0
  README.md
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change

#497 fix containerd CVE-2022-31030
  go.mod
  go.sum
Labels: kind/security
