Repository clusternet/clusternet, pull requests merged in 2022-07, with the labels that each got.

#401 prune localizations for replication scheduling
  pkg/hub/deployer/deployer.go
Labels: kind/bug

#385 override the helm chart
  examples/applications/globalization.yaml
  examples/applications/localization.yaml
  manifests/crds/apps.clusternet.io_descriptions.yaml
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  pkg/apis/apps/v1alpha1/description.go
  pkg/apis/apps/v1alpha1/localization.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/helm/helm.go
  pkg/hub/localizer/localizer.go
  pkg/hub/localizer/patch.go
  pkg/hub/localizer/patch_test.go
  pkg/utils/deployer.go
Labels: kind/feature

#359 aggregate child clusters workload status to desc
  pkg/agent/deployer/generic/generic.go
  pkg/controllers/apps/resource/resource.go
  pkg/utils/deployer.go
Labels: kind/feature

#406 fix localizations when scaling
  pkg/controllers/apps/subscription/subscription.go
Labels: kind/bug

#407 fix WATCH events on transforming and encoding
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/wrapper.go
Labels: kind/bug

#360 aggregate desc status to subscription and workload
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/controllers/apps/aggregatestatus/aggregatestatus.go
  pkg/hub/deployer/deployer.go
Labels: kind/feature

#408 removing Manifest finalizer in shadow api
  pkg/registry/shadow/template/transformer.go
  pkg/registry/shadow/template/transformer_test.go
Labels: kind/bug

#409 migrate docs to clusternet.io
  README.md
  docs/developer-guide.md
  docs/images/clusternet-apps-concepts.png
  docs/images/clusternet-arch.png
  docs/images/clusternet-horizontal-color.png
  docs/images/clusternet-in-a-nutshell.png
  docs/tutorials/checking-cluster-registration.md
  docs/tutorials/deploying-applications-to-multiple-clusters.md
  docs/tutorials/installing-clusternet-the-hard-way.md
  docs/tutorials/installing-clusternet-with-helm.md
  docs/tutorials/quick-installing-clusternet-locally.md
  docs/tutorials/replication-scheduling-to-multiple-clusters.md
  docs/tutorials/setting-overrides.md
  docs/tutorials/static-weight-scheduling-to-multiple-clusters.md
  docs/tutorials/visiting-child-clusters-with-rbac.md
Labels: kind/documentation

#411 fix apiservice informer cache not synced
  pkg/hub/hub.go
Labels: kind/bug

#413 fix bug of aggregate single node labels with no filter
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller_test.go
Labels: kind/bug

#416 ignore missing key error during json patch
  pkg/hub/localizer/localizer.go
  pkg/hub/localizer/patch.go
  pkg/hub/localizer/patch_test.go
Labels: kind/bug

#417 remove ignored fileds during appying overrides
  pkg/hub/localizer/localizer.go
  pkg/hub/localizer/patch.go
  pkg/hub/localizer/patch_test.go
  pkg/utils/deployer.go
Labels: kind/enhancement

#418 fix predictor address in scheduler
  pkg/scheduler/framework/plugins/predictor/predictor.go
Labels: kind/bug

#419 make DynamicAssigner as default PreAssign plugin
  pkg/scheduler/default_plugins.go
Labels: kind/enhancement

#420 add example on using dynamic dividing scheduling
  examples/dynamic-dividing-scheduling/nginx-deployment.yaml
  examples/dynamic-dividing-scheduling/nginx-svc.yaml
  examples/dynamic-dividing-scheduling/subscription.yaml
  examples/replication-scheduling/globalization.yaml
  examples/replication-scheduling/helm-chart-mysql.yaml
  examples/replication-scheduling/localization.yaml
  examples/replication-scheduling/nginx-deployment.yaml
  examples/replication-scheduling/nginx-svc.yaml
  examples/replication-scheduling/subscription.yaml
Labels: kind/examples

#377 update clusternet deployment files for new release
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
  deploy/scheduler/clusternet_scheduler_rbac.yaml
  examples/oci/oci-chart-mysql.yaml
  examples/replication-scheduling/globalization.yaml
  examples/replication-scheduling/helm-chart-mysql.yaml
  examples/replication-scheduling/localization.yaml
Labels: kind/change

#421 use pointer for podstatistics and resourceusage
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/bug

#365 add use-metrics-server flag in clusternet-agent deployment file
  deploy/agent/clusternet_agent_deployment.yaml
Labels: kind/change

#424 add WHAT param to specify building targets
  Makefile
  hack/lib/build.sh
  hack/make-rules/build.sh
  hack/make-rules/images.sh
Labels: kind/workflow, kind/enhancement

#429 add cluster type standard
  pkg/agent/option.go
  pkg/apis/clusters/v1beta1/types.go
Labels: kind/enhancement

#433 fix shadow crd scheme encoding
  pkg/hub/apiserver/shadow/customresource_handler.go
Labels: kind/bug

#437 using patch instead of UpdateStatus to prevent conflict
  pkg/scheduler/framework/plugins/defaultbinder/default_binder.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder_test.go
Labels: kind/enhancement

#436 add msc related crds
  deploy/agent/multicluster.x-k8s.io_serviceexports.yaml
  deploy/agent/multicluster.x-k8s.io_serviceimports.yaml
  deploy/hub/multicluster.x-k8s.io_serviceexports.yaml
  deploy/hub/multicluster.x-k8s.io_serviceimports.yaml
  manifests/crds/multicluster.x-k8s.io_serviceexports.yaml
  manifests/crds/multicluster.x-k8s.io_serviceimports.yaml
Labels: kind/feature, kind/apis
