Repository clusternet/clusternet, pull requests merged in 2022-10, with the labels that each got.

#501 ignore rescheduler when no available cluster
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#502 update codecov to v3
  .github/workflows/ci.yml
Labels: kind/workflow

#506 add mcs related cluster roles
  deploy/agent/clusternet_agent_rbac.yaml
Labels: kind/bug

#507 Fix non-nil pointer error about ClusterRoleBindingList
  pkg/registry/shadow/printers/internalversion/printers.go
Labels: kind/bug

#510 fix rollback-with-no-crd-error
  go.mod
  pkg/agent/deployer/generic/generic.go
Labels: kind/bug

#512 Add routes from parent cluster to child cluster pod
  hack/child1.yaml
  hack/child2.yaml
  hack/child3.yaml
  hack/local-running.sh
  hack/parent.yaml
Labels: kind/bug

#513 fix: mcs-api guarantee the ServiceImport ports' name and the port of service located on child cluster are same
  examples/scheduling-with-mcs-api/service-import.yaml
Labels: kind/bug
