Repository clusternet/clusternet, pull requests merged in 2022-08, with the labels that each got.

#435 add endpoint slice handler
  pkg/controllers/mcs/serviceexport_controller.go
Labels: kind/feature

#440 set max length of cluster name to 60
  pkg/agent/constant.go
Labels: kind/enhancement

#438 requeue Helm Release after helm repo got an update
  pkg/utils/chart.go
  pkg/utils/deployer.go
Labels: kind/bug

#442 add status patch rules for scheduler
  deploy/scheduler/clusternet_scheduler_rbac.yaml
Labels: kind/enhancement

#443 add flag peer-advertise-address
  pkg/hub/hub.go
  pkg/hub/options/options.go
Labels: kind/feature, kind/apis

#447 ignore custom metrics api group
  pkg/hub/apiserver/shadow/apiserver.go
Labels: kind/bug

#449 replace io/ioutil package with io package
  pkg/predictor/server.go
  pkg/scheduler/framework/plugins/predictor/predictor.go
Labels: kind/cleanup

#450 support scheduler workqueue metrics
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#451 add service import controller
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/hub/hub.go
  pkg/utils/endpointslice.go
Labels: kind/feature

#452 custom the namespace when registry a child cluster
  manifests/crds/clusters.clusternet.io_clusterregistrationrequests.yaml
  pkg/agent/agent.go
  pkg/agent/constant.go
  pkg/agent/option.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/hub/approver/approver.go
Labels: kind/feature, kind/apis

#453 fine tune some code in service export
  pkg/controllers/mcs/serviceexport_controller.go
Labels: kind/cleanup

#455 add mcs example
  examples/scheduling-with-mcs-api/scheduling/nginx-deployment.yaml
  examples/scheduling-with-mcs-api/scheduling/nginx-svc.yaml
  examples/scheduling-with-mcs-api/scheduling/service-export.yaml
  examples/scheduling-with-mcs-api/scheduling/subscription.yaml
  examples/scheduling-with-mcs-api/service-import.yaml
Labels: kind/examples

#460 fix nil assignments when collecting metrics
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/bug

#463 dryrun support for child clusters
  go.mod
  go.sum
Labels: kind/enhancement

#465 ignore apiservices self group checking
  pkg/hub/apiserver/shadow/priority.go
  pkg/hub/hub.go
Labels: kind/enhancement

#466 use apiservice group and version from SchemeGroupVersion
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/hub/apiserver/shadow/priority.go
Labels: kind/cleanup
