Repository clusternet/clusternet, pull requests merged in 2022-05, with the labels that each got.

#320 remove default log level settings
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/cleanup

#323 fix empty overrides deserialization
  pkg/hub/deployer/helm/helm.go
  pkg/utils/deployer.go
Labels: kind/bug

#326 fix helm target namespace
  pkg/agent/deployer/deployer.go
  pkg/agent/deployer/helm/helm.go
  pkg/hub/deployer/helm/helm.go
  pkg/utils/chart.go
Labels: kind/bug

#274 add replica estimator interface
  pkg/apis/scheduler/interface.go
Labels: kind/feature, kind/apis

#327 move owned-by-description label as annotation
  pkg/agent/deployer/generic/generic.go
  pkg/controllers/apps/resource/resource.go
  pkg/known/annotations.go
  pkg/known/labels.go
  pkg/utils/deployer.go
Labels: kind/bug

#328 use port-mapping endpoint for kind clusters on Docker Desktop
  hack/local-running.sh
Labels: kind/bug

#330 not trim uid
  pkg/registry/shadow/template/trimmer.go
  pkg/registry/shadow/template/trimmer_test.go
Labels: kind/bug

#332 fix feedInventory resource version
  pkg/controllers/apps/feedinventory/feedinventory.go
Labels: kind/bug

#334 apply cluster-aware overrides from Globalization
  pkg/hub/localizer/localizer.go
Labels: kind/feature

#311 fix cluster and service ip range
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/clusters/clusterstatus/network.go
Labels: kind/bug

#336 add framework for estimator server
  pkg/estimator/apis/types.go
  pkg/estimator/framework/interfaces/interface.go
  pkg/estimator/framework/interfaces/interface_copied.go
  pkg/estimator/framework/interfaces/types.go
  pkg/estimator/framework/runtime/framework.go
  pkg/estimator/framework/runtime/metrics_recorder.go
  pkg/estimator/framework/runtime/registry.go
  pkg/estimator/metrics/metrics.go
  pkg/estimator/metrics/profile_metrics.go
Labels: kind/feature

#339 check subscription binding clusters when managedcluster label deleted
  pkg/scheduler/scheduler.go
Labels: kind/bug

#340 fix enqueue in feedinventory
  pkg/controllers/apps/feedinventory/feedinventory.go
Labels: kind/bug

#348 fix CVE GHSA-hp87-p4gw-j4gq
  go.mod
  go.sum
Labels: kind/security

#349 renaming to predictor
  pkg/apis/scheduler/interface.go
  pkg/estimator/metrics/profile_metrics.go
  pkg/predictor/apis/types.go
  pkg/predictor/framework/interfaces/interface.go
  pkg/predictor/framework/interfaces/interface_copied.go
  pkg/predictor/framework/interfaces/types.go
  pkg/predictor/framework/runtime/framework.go
  pkg/predictor/framework/runtime/metrics_recorder.go
  pkg/predictor/framework/runtime/registry.go
  pkg/predictor/metrics/metrics.go
  pkg/predictor/metrics/profile_metrics.go
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/apis/types.go
  pkg/scheduler/default_plugins.go
  pkg/scheduler/framework/interfaces/interface.go
  pkg/scheduler/framework/runtime/framework.go
Labels: kind/change

#343 fix bug about rollback sync condition judge
  pkg/agent/deployer/generic/generic.go
  pkg/hub/deployer/generic/generic.go
  pkg/known/constant.go
  pkg/utils/deployer.go
  pkg/utils/deployer_test.go
  pkg/utils/slice.go
Labels: kind/bug

#346 add default predictor
  pkg/predictor/default_plugins.go
  pkg/predictor/framework/plugins/defaultaggregate/default_aggregate.go
  pkg/predictor/framework/plugins/defaultaggregate/default_aggregate_test.go
  pkg/predictor/framework/plugins/defaultcompute/default_compute.go
  pkg/predictor/framework/plugins/defaultcompute/default_compute_test.go
  pkg/predictor/framework/plugins/helper/normalize_score.go
  pkg/predictor/framework/plugins/helper/normalize_score_test.go
  pkg/predictor/framework/plugins/names/names.go
  pkg/predictor/framework/plugins/registry.go
  pkg/predictor/framework/plugins/tainttoleration/taint_toleration.go
  pkg/predictor/framework/plugins/tainttoleration/taint_toleration_test.go
  pkg/predictor/predictor.go
  pkg/predictor/server.go
  pkg/utils/resource.go
Labels: kind/feature

#352 fix resource controller run more than one
  pkg/agent/deployer/generic/generic.go
Labels: kind/bug

#355 starts default predictor in clusternet-agent
  pkg/agent/agent.go
  pkg/predictor/server.go
Labels: kind/feature

#356 optimize context usage in clusternet-agent
  cmd/clusternet-agent/app/app.go
  pkg/agent/agent.go
  pkg/agent/status_manager.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/change, kind/enhancement
