Repository clusternet/clusternet, pull requests merged in 2022-04, with the labels that each got.

#283 add apis for dividing scheduling
  manifests/crds/apps.clusternet.io_bases.yaml
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/feedinventory.go
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_feedinventory.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/feedinventory.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/generated/informers/externalversions/apps/v1alpha1/feedinventory.go
  pkg/generated/informers/externalversions/apps/v1alpha1/interface.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/apps/v1alpha1/expansion_generated.go
  pkg/generated/listers/apps/v1alpha1/feedinventory.go
Labels: kind/change, kind/apis

#285 update fedinventory shortname
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  pkg/apis/apps/v1alpha1/feedinventory.go
Labels: kind/change

#289 minor update FeedInventory apis
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/feedinventory.go
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: kind/change, kind/apis

#290 fix apiversion assignments with groupversion
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
Labels: kind/bug

#294 optimize ownerReferences with NewControllerRef
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/helm/helm.go
Labels: kind/cleanup

#291 use healthz to report cluster status with a lower version
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/apis/clusters/v1beta1/types.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/enhancement

#292 add static replica dividing
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/algorithm/dividing/static.go
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/algorithm/generic_test.go
  pkg/scheduler/algorithm/interface.go
  pkg/scheduler/framework/interfaces/interface.go
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder_test.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/scheduler.go
  pkg/utils/feed.go
Labels: kind/feature, kind/change, kind/apis

#286 add FeedInventory controller
  pkg/controllers/apps/feedinventory/deployment/deployment.go
  pkg/controllers/apps/feedinventory/deployment/deployment_test.go
  pkg/controllers/apps/feedinventory/feedinventory.go
  pkg/controllers/apps/feedinventory/feedinventory_test.go
  pkg/controllers/apps/feedinventory/registry.go
  pkg/controllers/apps/feedinventory/replicaset/replicaset.go
  pkg/controllers/apps/feedinventory/replicaset/replicaset_test.go
  pkg/controllers/apps/feedinventory/statefulset/statefulset.go
  pkg/controllers/apps/feedinventory/statefulset/statefulset_test.go
  pkg/controllers/apps/feedinventory/utils/utils.go
  pkg/controllers/apps/feedinventory/utils/utils_test.go
  pkg/features/features.go
  pkg/hub/deployer/deployer.go
Labels: kind/feature, kind/change, kind/apis

#295 fix static division algorithm
  pkg/scheduler/algorithm/dividing/static.go
  pkg/scheduler/algorithm/dividing/static_test.go
  pkg/scheduler/algorithm/generic_test.go
Labels: kind/bug

#297 populate Localizations for dividing scheduling
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/utils.go
  pkg/scheduler/algorithm/dividing/static.go
  pkg/scheduler/algorithm/generic_test.go
  pkg/utils/feed.go
Labels: kind/feature

#298 add example on static weight scheduling
  docs/tutorials/deploying-applications-to-multiple-clusters.md
  docs/tutorials/replication-scheduling-to-multiple-clusters.md
  docs/tutorials/setting-overrides.md
  docs/tutorials/static-weight-scheduling-to-multiple-clusters.md
  examples/static-dividing-scheduling/nginx-deployment.yaml
  examples/static-dividing-scheduling/nginx-svc.yaml
  examples/static-dividing-scheduling/subscription.yaml
Labels: kind/documentation

#301 do not rollback in-deleting Description
  pkg/agent/deployer/generic/generic.go
  pkg/controllers/apps/resource/resource.go
Labels: kind/bug

#287 update deployment scripts for v0.9.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
Labels: kind/change

#304 register FeedInventory
  pkg/apis/apps/v1alpha1/register.go
Labels: kind/bug

#305 fix HelmRelease status update error
  pkg/utils/deployer.go
Labels: kind/bug

#306 fix feedinventories creation
  deploy/scheduler/clusternet_scheduler_rbac.yaml
  pkg/hub/deployer/deployer.go
  pkg/hub/deployer/utils.go
Labels: kind/bug

#308 fix empty Base UID when populating Localizatios
  pkg/hub/deployer/deployer.go
Labels: kind/bug

#309 fix: releasename when deploy helm charts
  pkg/utils/deployer.go
Labels: kind/bug

#303 update CODEOWNERS rules
  CODEOWNERS
Labels: kind/workflow

#312 updating docs on checking cluster registration status
  README.md
  docs/tutorials/checking-cluster-registration.md
  docs/tutorials/installing-clusternet-the-hard-way.md
  docs/tutorials/installing-clusternet-with-helm.md
  docs/tutorials/quick-installing-clusternet-locally.md
Labels: kind/documentation

#313 fix repeat import
  pkg/controllers/apps/feedinventory/feedinventory.go
Labels: kind/cleanup

#314 add extra arg threadiness for hub
  pkg/hub/hub.go
  pkg/hub/options/options.go
  pkg/known/constant.go
Labels: kind/feature

#316 fix resource already exists for shadow apis
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/trimmer.go
  pkg/registry/shadow/template/trimmer_test.go
Labels: kind/bug

#317 add annotation for skipping validation
  pkg/known/annotations.go
  pkg/registry/shadow/template/rest.go
Labels: kind/feature
