Repository clusternet/clusternet, pull requests merged in 2023-11, with the labels that each got.

#761 set the default log verbosity level to 2
  pkg/utils/options.go
Labels: kind/enhancement

#765 add priority api for subscription
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/apis/apps/v1alpha1/subscription.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/applyconfiguration/apps/v1alpha1/subscriptionspec.go
Labels: kind/apis

#756 improve performance of controller
  pkg/controllermanager/deployer/deployer.go
  pkg/controllermanager/deployer/helm/helm.go
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/known/constant.go
  pkg/utils/deployer.go
  pkg/utils/feed.go
Labels: kind/enhancement, kind/performance

#766 add feature gate ClusterInit
  go.mod
  go.sum
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/status_manager.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/apis/clusters/v1beta1/zz_generated.deepcopy.go
  pkg/controllermanager/approver/approver.go
  pkg/controllermanager/controllermanager.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/features/features.go
  pkg/generated/applyconfiguration/clusters/v1beta1/managedclusterspec.go
  pkg/known/annotations.go
  pkg/known/taints.go
  pkg/utils/cluster.go
  pkg/utils/cluster_test.go
Labels: kind/feature

#768 fix type assertion when receiving DeletedFinalStateUnknown event
  pkg/controllers/apps/resource/resource.go
Labels: kind/bug

#767 bump priority queue into clusternet-scheduler
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/internal/heap/heap.go
  pkg/scheduler/internal/queue/queue.go
  pkg/scheduler/internal/queue/queue_test.go
  pkg/scheduler/scheduler.go
Labels: kind/feature
