Repository clusternet/clusternet, pull requests merged in 2023-03, with the labels that each got.

#622 pass down cluster ID to replicas predictor
  pkg/apis/scheduler/interface.go
  pkg/scheduler/framework/plugins/predictor/predictor.go
Labels: kind/feature

#623 bump controller-gen to v0.10.0
  Makefile
  manifests/crds/apps.clusternet.io_bases.yaml
  manifests/crds/apps.clusternet.io_descriptions.yaml
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  manifests/crds/apps.clusternet.io_globalizations.yaml
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  manifests/crds/apps.clusternet.io_localizations.yaml
  manifests/crds/apps.clusternet.io_manifests.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  manifests/crds/clusters.clusternet.io_clusterregistrationrequests.yaml
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
Labels: kind/change

#628 add wait parameter on helm uninstall
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/utils/chart.go
Labels: kind/feature

#636 validate name when creating shadow namespace
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#635 add helm options upgradeAtomic parameter
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/utils/chart.go
Labels: kind/feature

#632 simplify the algorithm for merging feed replicas
  .gitignore
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/interfaces/types_test.go
  pkg/scheduler/framework/plugins/defaultassigner/algorithm.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic_test.go
Labels: kind/enhancement

#638 introduce new component clusternet-controller-manager
  cmd/clusternet-controller-manager/app/app.go
  cmd/clusternet-controller-manager/app/context/context.go
  cmd/clusternet-controller-manager/app/controllermanager.go
  cmd/clusternet-controller-manager/app/options/options.go
  cmd/clusternet-controller-manager/controller-manager.go
Labels: kind/change

#640 add gci linter back
  .golangci.yml
  cmd/clusternet-controller-manager/app/app.go
  cmd/clusternet-controller-manager/app/context/context.go
  cmd/clusternet-controller-manager/app/controllermanager.go
  cmd/clusternet-controller-manager/app/options/options.go
  cmd/clusternet-controller-manager/controller-manager.go
  pkg/utils/version.go
Labels: kind/enhancement

#644 fix: do deepcopy before add finalizer
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/controllers/misc/secret/secret.go
Labels: kind/bug

#642 use namespaced name of Subscription for new Bases
  pkg/hub/deployer/deployer.go
Labels: kind/bug
