Repository clusternet/clusternet, pull requests merged in 2023-04, with the labels that each got.

#646 prune leftover controllers from clusternet-hub
  pkg/hub/hub.go
  pkg/hub/options/options.go
Labels: kind/feature

#647 rename packages in clusternet controller manager
  cmd/clusternet-controller-manager/app/app.go
  pkg/controllermanager/approver/approver.go
  pkg/controllermanager/approver/constant.go
  pkg/controllermanager/context/context.go
  pkg/controllermanager/controllermanager.go
  pkg/controllermanager/deployer/deployer.go
  pkg/controllermanager/deployer/generic/generic.go
  pkg/controllermanager/deployer/helm/helm.go
  pkg/controllermanager/deployer/localizer/localizer.go
  pkg/controllermanager/deployer/localizer/patch.go
  pkg/controllermanager/deployer/localizer/patch_test.go
  pkg/controllermanager/deployer/utils.go
  pkg/controllermanager/options/options.go
Labels: kind/cleanup, kind/enhancement

#650 Add controllersDisabledByDefault in controller-manager
  cmd/clusternet-controller-manager/app/app.go
  pkg/controllermanager/context/context.go
  pkg/controllermanager/controllermanager.go
  pkg/controllermanager/options/options.go
Labels: kind/enhancement

#649 optimize packages structure in hub
  pkg/hub/apiserver/apiserver.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/exchanger/exchanger.go
  pkg/hub/exchanger/exchanger_test.go
  pkg/hub/metrics/metrics.go
  pkg/hub/registry/proxies/socket/metrics.go
  pkg/hub/registry/proxies/socket/rest.go
  pkg/hub/registry/proxies/socket/subresources/proxy.go
  pkg/hub/registry/shadow/printers/interface.go
  pkg/hub/registry/shadow/printers/internalversion/printers.go
  pkg/hub/registry/shadow/printers/storage/storage.go
  pkg/hub/registry/shadow/printers/tablegenerator.go
  pkg/hub/registry/shadow/printers/util/helpers.go
  pkg/hub/registry/shadow/template/rest.go
  pkg/hub/registry/shadow/template/rest_test.go
  pkg/hub/registry/shadow/template/scale.go
  pkg/hub/registry/shadow/template/transformer.go
  pkg/hub/registry/shadow/template/transformer_test.go
  pkg/hub/registry/shadow/template/trimmer.go
  pkg/hub/registry/shadow/template/trimmer_test.go
  pkg/hub/registry/shadow/template/wrapper.go
Labels: kind/cleanup

#589 bump clusternet v0.15.0 container images
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/controller-manager/clusternet_controller_manager_deployment.yaml
  deploy/controller-manager/clusternet_controller_manager_rbac.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
  pkg/features/features.go
  pkg/known/constant.go
Labels: kind/change, do-not-merge/hold

#655 fix feature gate usage of MultiClusterService
  pkg/features/features.go
Labels: kind/documentation

#658 install controller-manager for local running
  hack/local-running.sh
Labels: kind/enhancement

#657 fix error message in cluster status controller
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
Labels: kind/bug

#661 fix wrong status referring in framework
  pkg/predictor/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework.go
Labels: kind/bug

#659 bump k8s dependencies to 1.26
  go.mod
  go.sum
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/controllermanager/controllermanager.go
  pkg/controllers/apps/aggregatestatus/aggregatestatus.go
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/feedinventory/feedinventory.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterlifecycle/discovery/discovery.go
  pkg/controllers/clusters/clusterregistrationrequest/clusterregistrationrequest_controller.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/controllers/misc/secret/secret.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/informers/externalversions/factory.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/hub.go
  pkg/hub/options/options.go
  pkg/hub/registry/shadow/printers/internalversion/printers.go
  pkg/scheduler/scheduler.go
Labels: kind/dependencies

#667 fix validating serviceAccount token
  pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/cluster_reg_options_test.go
  pkg/agent/options/constant.go
Labels: kind/bug

#666 apply resources to child clusters with method PATCH
  go.mod
  pkg/known/annotations.go
  pkg/utils/deployer.go
Labels: kind/enhancement

#671 tighten rbac rules
  deploy/agent/clusternet_agent_rbac.yaml
  deploy/controller-manager/clusternet_controller_manager_rbac.yaml
  deploy/hub/clusternet_hub_rbac.yaml
  pkg/controllers/clusters/clusterlifecycle/discovery/manifest.go
Labels: kind/security

#663 bump dependency yacht to v0.4.0
  go.mod
  go.sum
Labels: kind/dependencies

#673 taint cluster with not-ready conditions
  go.mod
  go.sum
  pkg/controllermanager/controllermanager.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller_test.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/known/taints.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration_test.go
  pkg/scheduler/scheduler.go
  pkg/utils/deployer.go
  pkg/utils/deployer_test.go
  pkg/utils/taints/taints.go
  pkg/utils/taints/taints_test.go
Labels: kind/feature
