Repository clusternet/clusternet, pull requests merged in 2023-01, with the labels that each got.

#566 Updated metrics for clusternet-hub
  go.mod
  go.sum
  pkg/controllers/apps/aggregatestatus/aggregatestatus.go
  pkg/controllers/apps/base/base.go
  pkg/controllers/apps/description/description.go
  pkg/controllers/apps/feedinventory/feedinventory.go
  pkg/controllers/apps/globalization/globalization.go
  pkg/controllers/apps/helmchart/helmchart.go
  pkg/controllers/apps/helmrelease/helmrelease.go
  pkg/controllers/apps/localization/localization.go
  pkg/controllers/apps/manifest/manifest.go
  pkg/controllers/apps/subscription/subscription.go
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
  pkg/controllers/clusters/clusterregistrationrequest/clusterregistrationrequest_controller.go
  pkg/controllers/misc/secret/secret.go
  pkg/hub/hub.go
  pkg/hub/metrics/metrics.go
  pkg/registry/proxies/socket/metrics.go
  pkg/registry/proxies/socket/rest.go
Labels: kind/feature

#570 no need enqueue when FeedInventory feature disable
  pkg/hub/deployer/deployer.go
Labels: kind/enhancement

#567 add MAINTAINERS file
  MAINTAINERS.md
Labels: kind/change

#573 when request is not set, it needs to be filled by limits
  pkg/controllers/apps/feedinventory/utils/utils.go
  pkg/controllers/apps/feedinventory/utils/utils_test.go
Labels: kind/enhancement

#574 fix unexpected manifest deletion when delete ns in parent-child cluster
  pkg/registry/shadow/template/rest.go
Labels: kind/bug

#576 add chart option to replace crds before install or upgrade
  manifests/crds/apps.clusternet.io_helmcharts.yaml
  manifests/crds/apps.clusternet.io_helmreleases.yaml
  pkg/apis/apps/v1alpha1/helm.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/chart.go
Labels: kind/enhancement
