Repository clusternet/clusternet, pull requests merged in 2023-10, with the labels that each got.

#747 fix panic when the length of bindingClusters and replicas in subscription are not equal
  pkg/controllermanager/deployer/deployer.go
Labels: kind/bug

#749 Add mcs-related resource syncer role and rolebinding
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/hub/clusternet_hub_rbac.yaml
  pkg/controllermanager/approver/approver.go
  pkg/controllermanager/approver/constant.go
Labels: kind/enhancement

#755 add metrics server for controller-manager
  pkg/controllermanager/controllermanager.go
Labels: kind/feature
