Repository clusternet/clusternet, pull requests merged in 2023-08, with the labels that each got.

#724 refine description of labels aggregation
  pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/constant.go
Labels: kind/documentation

#723 filter localizations by label created-by
  pkg/controllermanager/deployer/deployer.go
Labels: kind/enhancement

#730 bump some dependencies
  go.mod
  go.sum
Labels: kind/dependencies

#732 remove healthCheckNodePort field when create a loadbalance service
  pkg/hub/registry/shadow/template/trimmer.go
  pkg/hub/registry/shadow/template/trimmer_test.go
Labels: kind/bug

#733 bump cluster-api to v1.5.1
  go.mod
  go.sum
Labels: kind/dependencies
