Repository clusternet/clusternet, pull requests merged in 2023-06, with the labels that each got.

#696 fix nil pointer panic
  pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go
Labels: kind/bug

#700 update api doc of FeedInventory
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  pkg/apis/apps/v1alpha1/feedinventory.go
Labels: kind/documentation

#701 add context to predictor http requests
  pkg/scheduler/framework/plugins/predictor/predictor.go
Labels: kind/enhancement

#703 add action fossa
  .github/workflows/fossa.yml
Labels: kind/workflow

#705 tolerate predicting failures on feasible clusters
  pkg/features/features.go
  pkg/scheduler/apis/defaults.go
  pkg/scheduler/apis/types.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/scheduler.go
Labels: kind/feature

#707 configurable client qps and burst to access child clusters
  Makefile
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/agent.go
  pkg/agent/deployer/deployer.go
  pkg/agent/deployer/helm/helm.go
  pkg/agent/status_manager.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/controllermanager/deployer/generic/generic.go
  pkg/controllermanager/deployer/helm/helm.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/utils/chart.go
  pkg/utils/deployer.go
  pkg/utils/kubeconfig.go
Labels: kind/enhancement, kind/performance

#708 get dynamic client from cache
  pkg/controllermanager/deployer/generic/generic.go
Labels: kind/enhancement, kind/performance

#709 agent-side generic deployer uses configurable qps and burst
  pkg/agent/agent.go
  pkg/agent/deployer/deployer.go
  pkg/utils/kubeconfig.go
Labels: kind/enhancement

#711 fix pruning obsolete feeds when running in pull mode
  pkg/agent/deployer/deployer.go
  pkg/controllermanager/deployer/deployer.go
Labels: kind/bug

#713 fix the merging algorithm when the previous target cluster is empty
  pkg/scheduler/framework/interfaces/types.go
  pkg/scheduler/framework/interfaces/types_test.go
Labels: kind/bug

#714 update labels created by clusternet controller manager
  pkg/controllermanager/approver/approver.go
  pkg/controllermanager/deployer/deployer.go
  pkg/controllermanager/deployer/helm/helm.go
  pkg/controllermanager/deployer/utils.go
  pkg/controllers/apps/feedinventory/feedinventory.go
  pkg/controllers/apps/resource/resource.go
  pkg/controllers/clusters/clusterlifecycle/discovery/discovery.go
  pkg/known/labels.go
  pkg/utils/resourceinformer.go
Labels: kind/bug

#706 bump clusternet container images to v0.16.0
  deploy/agent/clusternet_agent_deployment.yaml
  deploy/controller-manager/clusternet_controller_manager_deployment.yaml
  deploy/hub/clusternet_hub_deployment.yaml
  deploy/scheduler/clusternet_scheduler_deployment.yaml
  pkg/agent/deployer/deployer.go
Labels: do-not-merge/hold

#716 fix metadata precondition failure
  pkg/utils/deployer.go
Labels: kind/bug

#588 clean up legacy cluster lease
  pkg/agent/agent.go
Labels: kind/change, kind/cleanup, do-not-merge/hold
