Repository clusternet/clusternet, pull requests merged in 2023-02, with the labels that each got.

#577 bump go version to 1.18
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Makefile
  go.mod
  go.sum
  hack/verify-gofmt.sh
  pkg/apis/scheduler/interface.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/registry/shadow/printers/internalversion/printers.go
  pkg/registry/shadow/printers/tablegenerator.go
  pkg/utils/endpointslice.go
  pkg/utils/names_test.go
  pkg/utils/resourceinformer.go
Labels: kind/workflow, kind/change

#581 bump kubernetes dependencies to v1.24
  .golangci.yml
  Makefile
  go.mod
  go.sum
  manifests/crds/apps.clusternet.io_feedinventories.yaml
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/agent.go
  pkg/apis/scheduler/interface.go
  pkg/controllers/mcs/serviceimport_controller.go
  pkg/exchanger/exchanger.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/hub/apiserver/shadow/apiserver.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/hub/options/options.go
  pkg/predictor/framework/plugins/defaultaggregate/default_aggregate.go
  pkg/predictor/framework/plugins/defaultcompute/default_compute.go
  pkg/predictor/framework/plugins/registry.go
  pkg/predictor/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/plugins/defaultassigner/dynamic.go
  pkg/scheduler/framework/plugins/defaultassigner/static.go
  pkg/scheduler/framework/plugins/defaultbinder/default_binder.go
  pkg/scheduler/framework/plugins/predictor/predictor.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/utils/chart.go
Labels: dependencies, go

#584 bump golang version to 1.19
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Makefile
  go.mod
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
Labels: kind/change, go

#587 use codecov token in CI pipeline
  .github/workflows/ci.yml
Labels: kind/workflow

#586 migrate legacy self-cluster lease
  cmd/clusternet-agent/app/options.go
  manifests/crds/clusters.clusternet.io_clusterregistrationrequests.yaml
  manifests/crds/clusters.clusternet.io_managedclusters.yaml
  pkg/agent/agent.go
  pkg/apis/clusters/v1beta1/types.go
  pkg/utils/patch.go
Labels: kind/change

#591 fix CVE-2022-41723 on maliciously crafted HTTP/2 stream causing DoS for small requests
  go.mod
  go.sum
Labels: kind/security

#593 validate bootstrap token for cluster registration
  go.mod
  go.sum
  pkg/agent/option.go
  pkg/agent/option_test.go
Labels: kind/enhancement

#594 format the function name of tests
  pkg/scheduler/framework/plugins/defaultassigner/algorithm_test.go
  pkg/scheduler/scheduler_test.go
Labels: kind/enhancement

#595 optimize the validations of ClusterRegistrationOptions
  pkg/agent/agent.go
  pkg/agent/option.go
Labels: kind/enhancement

#597 bump k8s dependencies to 1.25.6
  go.mod
  go.sum
  manifests/crds/apps.clusternet.io_subscriptions.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/hub/apiserver/shadow/customresource_handler.go
  pkg/predictor/server.go
  pkg/registry/proxies/socket/rest.go
  pkg/registry/proxies/socket/subresources/proxy.go
  pkg/registry/shadow/template/rest.go
  pkg/registry/shadow/template/scale.go
Labels: kind/change, kind/security

#596 fix bugs in TestGenerateClusterName
  pkg/agent/agent_test.go
Labels: kind/enhancement

#598 triggering merge group checks
  .github/workflows/ci.yml
Labels: kind/workflow

#599 replace deprecated func ioutil.ReadFile
  pkg/scheduler/options/options.go
Labels: kind/enhancement

#601 use named flagsets for clusternet-scheduler
  cmd/clusternet-scheduler/app/app.go
  cmd/clusternet-scheduler/scheduler.go
  go.mod
  go.sum
  pkg/scheduler/options/options.go
  pkg/utils/flag.go
  pkg/utils/options.go
Labels: kind/change, kind/enhancement

#603 use named flagsets for clusternet-hub
  cmd/clusternet-hub/app/app.go
  cmd/clusternet-hub/hub.go
  pkg/hub/options/options.go
  pkg/utils/options.go
Labels: kind/enhancement

#604 add scheduler profile validate testcase
  pkg/scheduler/apis/validation_test.go
Labels: kind/tests

#607 format clusternet-agent options
  cmd/clusternet-agent/app/app.go
  cmd/clusternet-agent/app/options.go
  pkg/agent/agent.go
  pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/cluster_reg_options_test.go
  pkg/agent/options/constant.go
  pkg/agent/options/options.go
  pkg/agent/status_manager.go
Labels: kind/enhancement

#606 serve metrics in clusternet-scheduler
  cmd/clusternet-scheduler/app/app.go
  pkg/scheduler/options/options.go
  pkg/scheduler/scheduler.go
  pkg/utils/metrics.go
Labels: kind/feature

#608 serve metrics in clusternet-agent
  cmd/clusternet-agent/app/app.go
  pkg/agent/agent.go
  pkg/agent/options/options.go
Labels: kind/feature

#615 bump helm to v3.10.3
  go.mod
  go.sum
Labels: kind/change, dependencies, go

#616 bump golangci-lint to 1.51.2
  Makefile
Labels: kind/change, kind/tests

#618 minor update doc
  README.md
  ROADMAP.md
Labels: kind/documentation

#621 add mcs featuregate
  pkg/agent/agent.go
  pkg/features/features.go
  pkg/hub/hub.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: kind/feature, do-not-merge/hold
