Repository clusternet/clusternet, pull requests merged in 2023-12, with the labels that each got.

#771 remove unused param clusternetClient
  pkg/agent/deployer/generic/generic.go
Labels: kind/cleanup

#770 update status with crash protection
  pkg/agent/deployer/generic/generic.go
  pkg/utils/deployer.go
Labels: kind/bug, kind/enhancement

#777 add PostAssign stage into scheduler framework
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/framework/interfaces/interface.go
  pkg/scheduler/framework/runtime/framework.go
Labels: kind/feature, kind/apis
