Repository clusternet/clusternet, pull requests merged in 2023-05, with the labels that each got.

#674 migrate workloads from not-ready clusters to healthy spare clusters
  pkg/features/features.go
  pkg/scheduler/scheduler.go
Labels: kind/feature

#682 add missing child cluster token for hub proxy #680
  deploy/agent/clusternet_agent_deployment.yaml
Labels: kind/bug

#679 user-defined prefixes for label aggregation
  pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/constant.go
  pkg/agent/status_manager.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go
  pkg/controllers/clusters/clusterstatus/clusterstatus_controller_test.go
Labels: kind/feature

#683 fix missing clusternet-hub-proxy serviceaccount token
  deploy/hub/clusternet_hub_deployment.yaml
Labels: kind/bug

#681 support different format base name
  pkg/controllermanager/deployer/deployer.go
Labels: kind/bug

#687 update github action checkout to v3
  pkg/apis/.github/workflows/sync-with-upstream.yml
Labels: kind/workflow, github_actions

#690 configurable percentage of clusters to be scored for scheduling
  pkg/scheduler/algorithm/generic.go
  pkg/scheduler/apis/types.go
  pkg/scheduler/scheduler.go
Labels: kind/enhancement

#691 Optimize yacht controller in mcs controllers
  pkg/agent/agent.go
  pkg/controllermanager/controllermanager.go
  pkg/controllers/mcs/serviceexport_controller.go
  pkg/controllers/mcs/serviceimport_controller.go
Labels: kind/enhancement

#694 fix controller manager lease name
  pkg/controllermanager/options/options.go
Labels: kind/bug

#697 Clean warning in pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/cluster_reg_options.go
  pkg/agent/options/options.go
Labels: kind/cleanup
